name: Java CI/CD with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
  security-events: write
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'  # Ensure Java 22 is supported; otherwise, use '17' or '21'
        distribution: 'temurin'
        cache: maven  # Cache Maven dependencies to speed up builds

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test

  deploy:
    needs: build  # Ensure the build job completes successfully before deploying
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only deploy on pushes to the main branch

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'  # Ensure Java 22 is supported; otherwise, use '17' or '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

   
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
           image: dilpatrai/achievegpa
           registry: docker.io
           username: ${( secrets.DOCKER_USERNAME )}
           password: ${( secrets.DOCKER_PASSWORD )}
